name: Docker Image CI

on:
  push:
    branches: [develop]

jobs:

  buildandpush:
    name: Build ➡️ Push
    runs-on: ubuntu-latest
    env:
      DOCKER_FILE: Dockerfile

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build the Docker image
        run: |
          docker build . --rm=false -t ${{ secrets.DOCKERHUB_USERNAME }}/nemo:latest
          docker push masonhall/nemo:latest
